name: tnhsr
services:
  db:
    build:
      context: ./deploy/db
      args:
        admin_psw: ${DB_ADMIN_PSW}
        admin_user: ${DB_ADMIN_USER}
        name: ${DB_DBNAME}
        root_psw: ${DB_ROOT_PSW}
    command: --authentication_policy=*
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ${DB_VOL_PATH}:/var/lib/mysql
volumes:
  db-data:
    driver: local
