name: tnhsr
networks:
  internal:
    driver: bridge
services:
  db:
    build:
      args:
        db_admin_psw: ${DB_ADMIN_PSW}
        db_admin_user: ${DB_ADMIN_USER}
        db_name: ${DB_NAME}
        db_root_psw: ${DB_ROOT_PSW}
      context: .
      dockerfile: ./deploy/db/Dockerfile
    command: --authentication_policy=*
    networks:
      - internal
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ${DB_VOL_PATH}:/var/lib/mysql
  server:
    build:
      args:
        db_psw: ${DB_ADMIN_PSW}
        db_user: ${DB_ADMIN_USER}
        db_name: ${DB_NAME}
      context: .
      dockerfile: ./deploy/server/Dockerfile
    networks:
      - internal
    depends_on:
      - db
volumes:
  db-data:
    driver: local
